### ISSUE TITLE
Rails 4.2.1: secretary-rails breaks auto-save for `has_many :through`

### ISSUE THREAD

**Issue by ewr** [SCPR/secretary-rails#14]
We upgraded SCPRv4 to Rails 4.2.1 this week and found that trying to trying to autosave rundowns to associate episodes and segments stopped working. Basically it tries to save the rundown without an `episode_id`. In a test app, I was able to create minimal models that showed that a) the default Rails behavior for saving works and b) that the error condition is created when `tracks_association` is added for the rundowns.

Minimal models:

```ruby
class Episode < ActiveRecord::Base
  has_secretary
  has_many :rundowns
  has_many :segments, through: :rundowns

  tracks_association :rundowns
end

class Rundown < ActiveRecord::Base
  belongs_to :episode
  belongs_to :segment
end

class Segment < ActiveRecord::Base
  has_many :rundowns
  has_many :episodes, through: :rundowns
end
```

Without `tracks_association`:

```
irb(main):001:0> e = Episode.new
=> #<Episode id: nil, created_at: nil, updated_at: nil>
irb(main):002:0> s = Segment.new
=> #<Segment id: nil, created_at: nil, updated_at: nil>
irb(main):003:0> s.save
   (0.2ms)  begin transaction
  SQL (1.5ms)  INSERT INTO "segments" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2015-05-08 14:00:29.041412"], ["updated_at", "2015-05-08 14:00:29.041412"]]
   (0.7ms)  commit transaction
=> true
irb(main):004:0> e.segments << s
=> #<ActiveRecord::Associations::CollectionProxy [#<Segment id: 5, created_at: "2015-05-08 14:00:29", updated_at: "2015-05-08 14:00:29">]>
irb(main):005:0> e.save
   (0.1ms)  begin transaction
  SQL (2.2ms)  INSERT INTO "episodes" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2015-05-08 14:00:35.643652"], ["updated_at", "2015-05-08 14:00:35.643652"]]
  SQL (0.5ms)  INSERT INTO "rundowns" ("segment_id", "episode_id", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["segment_id", 5], ["episode_id", 3], ["created_at", "2015-05-08 14:00:35.647912"], ["updated_at", "2015-05-08 14:00:35.647912"]]
   (0.8ms)  commit transaction
=> true
```

With `tracks_association`:

```
irb(main):007:0> e = Episode.new
=> #<Episode id: nil, created_at: nil, updated_at: nil>
irb(main):008:0> s = Segment.new
=> #<Segment id: nil, created_at: nil, updated_at: nil>
irb(main):009:0> s.save
   (0.1ms)  begin transaction
  SQL (0.5ms)  INSERT INTO "segments" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2015-05-08 14:00:58.889439"], ["updated_at", "2015-05-08 14:00:58.889439"]]
   (2.2ms)  commit transaction
=> true
irb(main):010:0> e.segments << s
=> #<ActiveRecord::Associations::CollectionProxy [#<Segment id: 6, created_at: "2015-05-08 14:00:58", updated_at: "2015-05-08 14:00:58">]>
irb(main):011:0> e.save
   (0.1ms)  begin transaction
  SQL (0.5ms)  INSERT INTO "episodes" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2015-05-08 14:01:06.545339"], ["updated_at", "2015-05-08 14:01:06.545339"]]
  SQL (1.5ms)  INSERT INTO "rundowns" ("segment_id", "created_at", "updated_at") VALUES (?, ?, ?)  [["segment_id", 6], ["created_at", "2015-05-08 14:01:06.547891"], ["updated_at", "2015-05-08 14:01:06.547891"]]
SQLite3::ConstraintException: NOT NULL constraint failed: rundowns.episode_id: INSERT INTO "rundowns" ("segment_id", "created_at", "updated_at") VALUES (?, ?, ?)
   (1.8ms)  rollback transaction
ActiveRecord::StatementInvalid: SQLite3::ConstraintException: NOT NULL constraint failed: rundowns.episode_id: INSERT INTO "rundowns" ("segment_id", "created_at", "updated_at") VALUES (?, ?, ?)
```

**Comment by bricker** [comment]
Thanks Eric, I will take a look and fix this ASAP, I should be able to get something out by the end of the weekend.

**Comment by bricker** [comment]
Eric, thanks for the detailed report, I was able to quickly reproduce using your example and fixed the problem with e03c5952619975bd39e7a2ef61ac26088983bc5f .

This was my fault — at one point the library needs to cast the list of `before_add` and `before_remove` callbacks into Arrays so it can safely push multiple callbacks to it. For rails 4.0 and below, it was only casting those two lists, explicitly. For Rails 4.1+ it did an unnecessary brute-force cast of all collection callbacks. The method that was being called to do this got called twice for each model: once by Rails internally, and then again by Secretary, and it has a side-effect of appending the autosave hook (and a few destroy hooks too, which probably would have caused another problem at some point) to that list. So calling it a second time appended the callback to the list a second time, and the double-callback was causing the error.

To fix it, I pared it down to explicitly cast just those two callbacks (`before_add` and `before_remove`), bypassing the side-effects caused by using the other method (which was wrong in the first place anyways). I added a test which matches your example, it was failing before the fix and now it passes in all versions.

I released the 2.0.1 patch for this fix — please try it and let me know if it fixes your problem.

Thanks again!

**Comment by ewr** [comment]
Thanks Bryan. I re-added the `tracks_association :rundowns` and our tests still pass. :+1: 

I had to bump the version on outpost-secretary to loosen the constraint on secretary-rails... I forgot that `2.0.0rc1` __is__ `< 2`, so it confused me at first why going 2.0.0 to 2.0.1 broke it.

**Comment by bricker** [comment]
Great, thanks!

**Comment by bricker** [comment]
@ewr I just pushed outpost-secretary v0.1.2 to rubygems, it includes your gemspec update plus add a dependency on the "responders" gem to get the tests passing.

If you want, I'll add you as an owner to the gems under the SCPR org so you can push new versions to rubygems, I just need the e-mail associated with your rubygems account.

**Comment by ewr** [comment]
Thanks. Use e@ewr.is
